- `[x]` Backend: Add `PATCH /api/applications/:id/status` endpoint with audit logging
- `[x]` Backend: Add `GET /api/applications/:id` single application endpoint
- `[x]` Backend: Enhance `GET /api/stats` to include pending applications count
- `[x]` Frontend: Create `ApplicationReview.css` styles
- `[x]` Frontend: Create `ApplicationReview.jsx` with table, filters, detail drawer, actions
- `[x]` Frontend: Update `App.jsx` with new route
- `[x]` Frontend: Update `Sidebar.jsx` with new nav item + pending badge
- `[x]` Frontend: Enhance `Dashboard.jsx` with pending applications stat card
- `[x]` Bug Fix: Resolve `backToCatalog` error in `History.jsx`
- `[x]` Verify: Test visa application submission and review workflow
- `[x]` Create walkthrough (Phase 1)
- `[x]` **Phase 2: Forensic Analytics & Secure Export**
    - `[x]` `History.jsx`: Implement "Visual Analysis" mode with Recharts
    - `[x]` `History.jsx`: Create a secure CSV export utility
    - `[x]` `History.jsx`: Implement tabbed results interface
    - `[x]` `server.js`: Audit log all export actions
    - `[x]` Create walkthrough (Phase 2)
- `[x]` **Phase 3: Risk Assessment & Unified Profiles**
    - `[x]` `server.js`: Implement Backend Risk Scoring Engine
    - `[x]` `TravelerProfile.jsx`: Create detailed intelligence profile view
    - `[x]` `TravelerSearch.jsx`: Link search results to the new profile page
    - `[x]` `Processing.jsx`: Display real-time risk status during crossing
    - `[x]` `ApplicationReview.jsx`: Integrate risk status into adjudication drawer
    - `[x]` Create walkthrough (Phase 3)
- `[x]` **Phase 4: Digital Mission Documents (e-Visa Issuance)**
    - `[x]` `VisaDocument.jsx`: Create high-fidelity e-Visa printable template
    - `[x]` `server.js`: Add verification endpoint and issuance audit
    - `[x]` `ApplicationReview.jsx`: Add "Issue e-Visa" button and preview
    - `[x]` `Status.jsx`: Add "Download e-Visa" button to the status portal
    - `[x]` Verify: Complete end-to-end lifecycle from public submission to visa download
    - `[x]` Create final walkthrough (Phase 4)
- `[x]` **Phase 5: Mission Communication & Governance**
    - `[x]` `server.js`: Create `notifications` table and auto-log dispatch events
    - `[x]` `History.jsx`: Add Communication Dispatch Log template
    - `[x]` `Dashboard.jsx`: Add Dispatch Throughput stat card
    - `[x]` Verify: Adjudication/Issuance triggers communication entries
    - `[x]` Create final project walkthrough (All Phases)
- `[ ]` **Phase 6: Biometric Forensic Intelligence**
    - `[ ]` `Processing.jsx`: Integrate "Biometric Scanning" UI & Matching logic
    - `[ ]` `ApplicationReview.jsx`: Show photo integrity/match results in adjudication
    - `[ ]` `server.js`: Implement `simulatedFaceMatch` intelligence
    - `[ ]` Create final project walkthrough (Phase 6)
